// web/src/pages/meta/quality/index.tsx
import React, { useEffect, useState } from 'react';
import { PageContainer } from '@ant-design/pro-layout';
import { Row, Col, Card, Progress, message } from 'antd';
import { PieChartTwoTone, CheckCircleOutlined } from '@ant-design/icons';
import styles from './index.less';
import PieChart from '@/components/Chart/PieChart';
import { StatisticCard } from '@ant-design/pro-components';
import { queryQualityData } from './service';

const { Divider } = StatisticCard;

export default (): React.ReactNode => {
  const [qualityData, setQualityData] = useState<any>({});
  const [loading, setLoading] = useState<boolean>(true);
  const [databaseQualityData, setDatabaseQualityData] = useState<any>([{ type: 'noData', value: 1 }]);
  const [tableQualityData, setTableQualityData] = useState<any>([{ type: 'noData', value: 1 }]);
  const [columnQualityData, setColumnQualityData] = useState<any>([{ type: 'noData', value: 1 }]);
  const [tableCommentAccuracyData, setTableCommentAccuracyData] = useState<any>([{ type: 'noData', value: 1 }]);
  const [columnCommentAccuracyData, setColumnCommentAccuracyData] = useState<any>([{ type: 'noData', value: 1 }]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await queryQualityData();
        if (response.success) {
          const data = response.data;
          setQualityData(data);
          setDatabaseQualityData(data.databaseQualityDataList || [{ type: 'noData', value: 1 }]);
          setTableQualityData(data.tableQualityDataList || [{ type: 'noData', value: 1 }]);
          setColumnQualityData(data.columnQualityDataList || [{ type: 'noData', value: 1 }]);
          setTableCommentAccuracyData(data.tableCommentAccuracyDataList || [{ type: 'noData', value: 1 }]);
          setColumnCommentAccuracyData(data.columnCommentAccuracyDataList || [{ type: 'noData', value: 1 }]);
        } else {
          message.error('获取数据失败');
        }
      } catch (error) {
        console.error('获取元数据质量数据失败:', error);
        message.error('获取数据失败，请检查网络连接');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  const getQualityColor = (rate: number) => {
    if (rate >= 80) return '#52c41a';
    if (rate >= 60) return '#faad14';
    return '#ff4d4f';
  };

  return (
    <PageContainer title="数据字典质量大盘">
      <Row gutter={[16, 24]} style={{ marginTop: '10px' }}>
        <Col span={24}>
          <StatisticCard.Group className={styles.statisticGroup}>
            <StatisticCard
              statistic={{
                title: <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '16px' }}>🗄️</span>
                  数据库总数
                </span>,
                value: qualityData?.databaseCount || 0,
                status: 'default',
              }}
              loading={loading}
            />
            <Divider />
            <StatisticCard
              statistic={{
                title: <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '16px' }}>📋</span>
                  数据表总数
                </span>,
                value: qualityData?.tableCount || 0,
                status: 'success',
              }}
              loading={loading}
            />
            <Divider />
            <StatisticCard
              statistic={{
                title: <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '16px' }}>📝</span>
                  数据字段总数
                </span>,
                value: qualityData?.columnCount || 0,
                status: 'processing',
              }}
              loading={loading}
            />
          </StatisticCard.Group>
        </Col>
      </Row>

      <Row gutter={[16, 24]} style={{ marginTop: '15px' }}>
        <Col span={8}>
          <Card 
            title={<span><CheckCircleOutlined style={{ color: getQualityColor(qualityData?.databaseBusinessRate || 0) }} />&nbsp;数据库业务关联率</span>}
            bordered={false}
            className={styles.qualityCard}
          >
            <div style={{ textAlign: 'center', padding: '20px 0' }}>
              <Progress
                type="circle"
                percent={qualityData?.databaseBusinessRate || 0}
                strokeColor={getQualityColor(qualityData?.databaseBusinessRate || 0)}
                format={(percent) => `${percent}%`}
                size={120}
              />
              <div style={{ marginTop: '16px', fontSize: '14px', color: '#666' }}>
                已关联业务数据库占比
              </div>
            </div>
          </Card>
        </Col>
        <Col span={8}>
          <Card 
            title={<span><CheckCircleOutlined style={{ color: getQualityColor(qualityData?.tableCommentRate || 0) }} />&nbsp;数据表注释完备率</span>}
            bordered={false}
            className={styles.qualityCard}
          >
            <div style={{ textAlign: 'center', padding: '20px 0' }}>
              <Progress
                type="circle"
                percent={qualityData?.tableCommentRate || 0}
                strokeColor={getQualityColor(qualityData?.tableCommentRate || 0)}
                format={(percent) => `${percent}%`}
                size={120}
              />
              <div style={{ marginTop: '16px', fontSize: '14px', color: '#666' }}>
                有注释的数据表占比
              </div>
            </div>
          </Card>
        </Col>
        <Col span={8}>
          <Card 
            title={<span><CheckCircleOutlined style={{ color: getQualityColor(qualityData?.columnCommentRate || 0) }} />&nbsp;数据字段注释完备率</span>}
            bordered={false}
            className={styles.qualityCard}
          >
            <div style={{ textAlign: 'center', padding: '20px 0' }}>
              <Progress
                type="circle"
                percent={qualityData?.columnCommentRate || 0}
                strokeColor={getQualityColor(qualityData?.columnCommentRate || 0)}
                format={(percent) => `${percent}%`}
                size={120}
              />
              <div style={{ marginTop: '16px', fontSize: '14px', color: '#666' }}>
                有注释的数据字段占比
              </div>
            </div>
          </Card>
        </Col>
      </Row>

      <Row gutter={[16, 24]} style={{ marginTop: '15px' }}>
        <Col span={12}>
          <Card 
            title={<span><CheckCircleOutlined style={{ color: getQualityColor(qualityData?.tableAccuracyRate || 0) }} />&nbsp;数据表备注准确度</span>}
            bordered={false}
            className={styles.qualityCard}
          >
            <div style={{ textAlign: 'center', padding: '20px 0' }}>
              <Progress
                type="circle"
                percent={qualityData?.tableAccuracyRate || 0}
                strokeColor={getQualityColor(qualityData?.tableAccuracyRate || 0)}
                format={(percent) => `${percent}%`}
                size={120}
              />
              <div style={{ marginTop: '16px', fontSize: '14px', color: '#666' }}>
                数据表备注准确度评估
              </div>
            </div>
          </Card>
        </Col>
        <Col span={12}>
          <Card 
            title={<span><CheckCircleOutlined style={{ color: getQualityColor(qualityData?.columnAccuracyRate || 0) }} />&nbsp;数据字段备注准确度</span>}
            bordered={false}
            className={styles.qualityCard}
          >
            <div style={{ textAlign: 'center', padding: '20px 0' }}>
              <Progress
                type="circle"
                percent={qualityData?.columnAccuracyRate || 0}
                strokeColor={getQualityColor(qualityData?.columnAccuracyRate || 0)}
                format={(percent) => `${percent}%`}
                size={120}
              />
              <div style={{ marginTop: '16px', fontSize: '14px', color: '#666' }}>
                数据字段备注准确度评估
              </div>
            </div>
          </Card>
        </Col>
      </Row>

      <Row gutter={[16, 24]} style={{ marginTop: '15px' }}>
        <Col span={12}>
          <Card 
            title={<span><PieChartTwoTone />&nbsp;数据库业务关联情况</span>} 
            bordered={false}
            className={styles.chartCard}
          >
            <PieChart data={databaseQualityData} loading={loading} height={330} />
          </Card>
        </Col>
        <Col span={12}>
          <Card 
            title={<span><PieChartTwoTone />&nbsp;数据表注释完备情况</span>} 
            bordered={false}
            className={styles.chartCard}
          >
            <PieChart data={tableQualityData} loading={loading} height={330} />
          </Card>
        </Col>
      </Row>

      <Row gutter={[16, 24]} style={{ marginTop: '15px' }}>
        <Col span={12}>
          <Card 
            title={<span><PieChartTwoTone />&nbsp;数据字段注释完备情况</span>} 
            bordered={false}
            className={styles.chartCard}
          >
            <PieChart data={columnQualityData} loading={loading} height={330} />
          </Card>
        </Col>
        <Col span={12}>
          <Card 
            title={<span><PieChartTwoTone />&nbsp;表注释准确度分布</span>} 
            bordered={false}
            className={styles.chartCard}
          >
            <PieChart data={tableCommentAccuracyData} loading={loading} height={330} />
          </Card>
        </Col>
      </Row>

      <Row gutter={[16, 24]} style={{ marginTop: '15px' }}>
        <Col span={12}>
          <Card 
            title={<span><PieChartTwoTone />&nbsp;字段注释准确度分布</span>} 
            bordered={false}
            className={styles.chartCard}
          >
            <PieChart data={columnCommentAccuracyData} loading={loading} height={330} />
          </Card>
        </Col>
      </Row>
    </PageContainer>
  );
};

// frontend/apps/web-antd/src/views/meta/quality/index.vue
<script lang="ts" setup>
import type { EchartsUIType } from '@vben/plugins/echarts';

import { nextTick, onMounted, ref } from 'vue';

import { EchartsUI, useEcharts } from '@vben/plugins/echarts';
import { Card, Col, Progress, Row, Statistic } from 'ant-design-vue';

import { baseRequestClient } from '#/api/request';

interface PieItem {
  type: string;
  value: number;
}

interface QualityData {
  columnAccuracyRate?: number | string;
  columnCommentAccuracyDataList?: PieItem[];
  columnCommentRate?: number | string;
  columnCount?: number | string;
  columnQualityDataList?: PieItem[];
  databaseBusinessRate?: number | string;
  databaseCount?: number | string;
  databaseQualityDataList?: PieItem[];
  tableAccuracyRate?: number | string;
  tableCommentAccuracyDataList?: PieItem[];
  tableCommentRate?: number | string;
  tableCount?: number | string;
  tableQualityDataList?: PieItem[];
}

const loading = ref(true);
const qualityData = ref<QualityData>({});

const dbQualityChartRef = ref<EchartsUIType>();
const tableQualityChartRef = ref<EchartsUIType>();
const columnQualityChartRef = ref<EchartsUIType>();
const tableAccChartRef = ref<EchartsUIType>();
const columnAccChartRef = ref<EchartsUIType>();

const { renderEcharts: renderDbQuality } = useEcharts(dbQualityChartRef);
const { renderEcharts: renderTableQuality } = useEcharts(tableQualityChartRef);
const { renderEcharts: renderColumnQuality } = useEcharts(columnQualityChartRef);
const { renderEcharts: renderTableAcc } = useEcharts(tableAccChartRef);
const { renderEcharts: renderColumnAcc } = useEcharts(columnAccChartRef);

function toNumber(value: number | string | undefined) {
  if (typeof value === 'number') return value;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function normalizePieData(data?: PieItem[]) {
  if (!data || data.length === 0) return [{ type: '暂无数据', value: 1 }];
  return data.map((item) => ({
    type: item.type,
    value: toNumber(item.value),
  }));
}

function getQualityColor(rate: number) {
  if (rate >= 80) return '#52c41a';
  if (rate >= 60) return '#faad14';
  return '#ff4d4f';
}

function renderPie(
  render: (option: Record<string, any>) => void,
  title: string,
  data?: PieItem[],
) {
  const pieData = normalizePieData(data);
  render({
    legend: {
      bottom: '2%',
      left: 'center',
    },
    series: [
      {
        data: pieData.map((item) => ({ name: item.type, value: item.value })),
        itemStyle: {
          borderRadius: 8,
          borderWidth: 2,
        },
        label: {
          formatter: '{b}: {d}%',
        },
        name: title,
        radius: ['45%', '70%'],
        type: 'pie',
      },
    ],
    tooltip: {
      trigger: 'item',
    },
  });
}

function renderAllCharts() {
  renderPie(
    renderDbQuality,
    '数据库业务关联情况',
    qualityData.value.databaseQualityDataList,
  );
  renderPie(renderTableQuality, '数据表注释完备情况', qualityData.value.tableQualityDataList);
  renderPie(
    renderColumnQuality,
    '数据字段注释完备情况',
    qualityData.value.columnQualityDataList,
  );
  renderPie(
    renderTableAcc,
    '表注释准确度分布',
    qualityData.value.tableCommentAccuracyDataList,
  );
  renderPie(
    renderColumnAcc,
    '字段注释准确度分布',
    qualityData.value.columnCommentAccuracyDataList,
  );
}

function resolveQualityData(response: any): QualityData {
  if (response?.data?.databaseCount !== undefined) return response.data as QualityData;
  if (response?.databaseCount !== undefined) return response as QualityData;
  if (response?.data?.data) return response.data.data as QualityData;
  return {};
}

async function fetchQualityData() {
  loading.value = true;
  try {
    const response = await baseRequestClient.get('/v1/meta/quality/info');
    qualityData.value = resolveQualityData(response);
  } finally {
    loading.value = false;
    await nextTick();
    renderAllCharts();
  }
}

onMounted(fetchQualityData);
</script>

<template>
  <div class="p-5">
    <Row :gutter="[16, 16]">
      <Col :md="8" :xs="24">
        <Card :loading="loading">
          <Statistic title="数据库总数" :value="toNumber(qualityData.databaseCount)" />
        </Card>
      </Col>
      <Col :md="8" :xs="24">
        <Card :loading="loading">
          <Statistic title="数据表总数" :value="toNumber(qualityData.tableCount)" />
        </Card>
      </Col>
      <Col :md="8" :xs="24">
        <Card :loading="loading">
          <Statistic title="数据字段总数" :value="toNumber(qualityData.columnCount)" />
        </Card>
      </Col>
    </Row>

    <Row :gutter="[16, 16]" class="mt-4">
      <Col :md="8" :xs="24">
        <Card title="数据库业务关联率" :loading="loading">
          <div class="circle-wrap">
            <Progress
              type="circle"
              :percent="toNumber(qualityData.databaseBusinessRate)"
              :stroke-color="getQualityColor(toNumber(qualityData.databaseBusinessRate))"
            />
          </div>
        </Card>
      </Col>
      <Col :md="8" :xs="24">
        <Card title="数据表注释完备率" :loading="loading">
          <div class="circle-wrap">
            <Progress
              type="circle"
              :percent="toNumber(qualityData.tableCommentRate)"
              :stroke-color="getQualityColor(toNumber(qualityData.tableCommentRate))"
            />
          </div>
        </Card>
      </Col>
      <Col :md="8" :xs="24">
        <Card title="数据字段注释完备率" :loading="loading">
          <div class="circle-wrap">
            <Progress
              type="circle"
              :percent="toNumber(qualityData.columnCommentRate)"
              :stroke-color="getQualityColor(toNumber(qualityData.columnCommentRate))"
            />
          </div>
        </Card>
      </Col>
    </Row>

    <Row :gutter="[16, 16]" class="mt-4">
      <Col :md="12" :xs="24">
        <Card title="数据表备注准确度" :loading="loading">
          <div class="circle-wrap">
            <Progress
              type="circle"
              :percent="toNumber(qualityData.tableAccuracyRate)"
              :stroke-color="getQualityColor(toNumber(qualityData.tableAccuracyRate))"
            />
          </div>
        </Card>
      </Col>
      <Col :md="12" :xs="24">
        <Card title="数据字段备注准确度" :loading="loading">
          <div class="circle-wrap">
            <Progress
              type="circle"
              :percent="toNumber(qualityData.columnAccuracyRate)"
              :stroke-color="getQualityColor(toNumber(qualityData.columnAccuracyRate))"
            />
          </div>
        </Card>
      </Col>
    </Row>

    <Row :gutter="[16, 16]" class="mt-4">
      <Col :md="12" :xs="24">
        <Card title="数据库业务关联情况" :loading="loading">
          <EchartsUI ref="dbQualityChartRef" class="h-[330px]" />
        </Card>
      </Col>
      <Col :md="12" :xs="24">
        <Card title="数据表注释完备情况" :loading="loading">
          <EchartsUI ref="tableQualityChartRef" class="h-[330px]" />
        </Card>
      </Col>
    </Row>

    <Row :gutter="[16, 16]" class="mt-4">
      <Col :md="12" :xs="24">
        <Card title="数据字段注释完备情况" :loading="loading">
          <EchartsUI ref="columnQualityChartRef" class="h-[330px]" />
        </Card>
      </Col>
      <Col :md="12" :xs="24">
        <Card title="表注释准确度分布" :loading="loading">
          <EchartsUI ref="tableAccChartRef" class="h-[330px]" />
        </Card>
      </Col>
    </Row>

    <Row :gutter="[16, 16]" class="mt-4">
      <Col :md="12" :xs="24">
        <Card title="字段注释准确度分布" :loading="loading">
          <EchartsUI ref="columnAccChartRef" class="h-[330px]" />
        </Card>
      </Col>
    </Row>
  </div>
</template>

<style scoped>
.circle-wrap {
  display: flex;
  justify-content: center;
  padding: 16px 0;
}
</style>
